### ISSUE TITLE
RetrieveExample.py import error

### ISSUE THREAD

**Issue by tkjUser** [LarsBentsen/FFTransformer#2]
There is an import error when I want to run  RetrieveExample.py which is caused by sentence `import utils_geom`,I try to install torch_geometric to import  utils_geom by sentence `from torch_geometric.utils import utils_geom`. I want to know how I can achieve sentence `import utils_geom` without error. Is utils_geom a python package or a custom package？Looking forward to your reply.

**Comment by LarsBentsen** [comment]
Thank you for bringing this to my attention. I forgot to include the utils_geom.py file in the repository. Instead of using this file, I have moved my 'distance_coord' function, which estimates the distance between two coordinates (in meters),  into the RetrieveExample.py script. I also noticed that the requirements.txt file did not include the 'retrieve' package to download data. This is now also included. I will close this issue now, but please re-open it if this does not resolve the problems.
